CREATE DATABASE QuanLyThuVien;
USE QuanLyThuVien;

CREATE TABLE Books (
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Quantity INT DEFAULT 0
);

CREATE TABLE Readers (
    ReaderID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Phone VARCHAR(20)
);